[build]
  command   = "npm run build"
  publish   = ".next"

[build.environment]
  NODE_VERSION                  = "20"
  PRISMA_CLI_QUERY_ENGINE_TYPE  = "library"
  PRISMA_CLIENT_ENGINE_TYPE     = "library"

[[plugins]]
  package = "@netlify/plugin-nextjs"
